const HORIZONTAL_ALIGNMENT_TYPE = Object.freeze({
  CENTER: 'CENTER',
  START: 'START',
  END: 'END',
  BETWEEN: 'BETWEEN',
  AROUND: 'AROUND',
});

const FONT_AWESOME_SIZE = Object.freeze({
  ONE: 'ONE',
  TWO: 'TWO',
  THREE: 'THREE',
  FOUR: 'FOUR',
  FIVE: 'FIVE',
});

const SERVICE_TYPE = Object.freeze({
  ANGELLIST: 'ANGELLIST',
  BITBUCKET: 'BITBUCKET',
  CODEPEN: 'CODEPEN',
  FACEBOOK: 'FACEBOOK',
  GITHUB: 'GITHUB',
  TWITTER: 'TWITTER',
});

const TARGET = Object.freeze({
  BLANK: 'BLANK',
  SELF: 'SELF',
  PARENT: 'PARENT',
  TOP: 'TOP',
});

const TOOLTIP_PLACEMENT = Object.freeze({
  AUTO: 'AUTO',
  AUTO_START: 'AUTO_START',
  AUTO_END: 'AUTO_END',
  TOP: 'TOP',
  TOP_START: 'TOP_START',
  TOP_END: 'TOP_END',
  RIGHT: 'RIGHT',
  RIGHT_START: 'RIGHT_START',
  RIGHT_END: 'RIGHT_END',
  BOTTOM: 'BOTTOM',
  BOTTOM_START: 'BOTTOM_START',
  BOTTOM_END: 'BOTTOM_END',
  LEFT: 'LEFT',
  LEFT_START: 'LEFT_START',
  LEFT_END: 'LEFT_END',
});

export {
  HORIZONTAL_ALIGNMENT_TYPE,
  FONT_AWESOME_SIZE,
  SERVICE_TYPE,
  TARGET,
  TOOLTIP_PLACEMENT,
};
